from src.modular_inference_methods.interface_prediction.ml_based import *
from src.modular_inference_methods.interface_prediction import additive_predictor, cn_predictor, top_5_predictor
from src.modular_inference_methods import interaction_prediction